- hosts: all
  name: Configure server
  user: vagrant
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    project_name: "{{ project_name }}"
    project_owner: "{{ project_owner }}"
    git_repo_url: "https://github.com/{{ project_owner }}/{{ project_name }}.git"
    git_repo_branch: "{{ project_version }}"
    cap_deployment: "{{ cap_deployment }}"
    solr_fqdn: "localhost"
    solr_cores:
      - ident: "{{ project_name }}"
        type: "hyrax"
    tomcat_applications:
      - app_name: "fedora"
        shut_port: "8008"
        conn_port: "8080"
        rproxy_path: "fcrepo"
    mysql_databases:
      - name: "fedora"
        collation: "utf8_bin"
        encoding: "utf8"
        state: "present"
      - name: "{{ project_name }}"
        collation: "utf8_bin"
        encoding: "utf8"
        state: "present"
      - name: "{{ project_name }}-test"
        collation: "utf8_bin"
        encoding: "utf8"
        state: "present"
    mysql_users:
      - name: "{{ fcdb_user }}"
        host: "localhost"
        password: "{{ fcdb_password }}"
        priv: "fedora.*:ALL"
        state: "present"
      - name: "{{ samvera_db_user }}"
        host: "localhost"
        password: "{{ samvera_db_password }}"
        priv: "{{ project_name }}.*:ALL/{{ project_name }}-test.*:ALL"
        state: "present"
    fedora_db_user: "{{ fcdb_user }}"
    fedora_db_password: "{{ fcdb_password }}"
    fedora_db_host: "localhost"
    fedora_db_port: "3306"
    fedora_db_name: "fedora"
    fedora_admin_user: "{{ fc_admin_user }}"
    fedora_admin_password: "{{ fc_admin_password }}"
    fedora_server_fqdn: "localhost"
  roles:
    - { role: uclalib_role_rhel7repos }
    - { role: uclalib_role_epel }
    - { role: uclalib_role_mysql, mysql_install_version: '5.6' }
    - { role: uclalib_role_uclalibrepo }
    - { role: uclalib_role_samvera_basepackages }
    - { role: uclalib_role_java, oracle_java_version: '1.8.0_181' }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_solr7, solr_version: '7.4.0' }
    - { role: uclalib_role_tomcat }
    - { role: uclalib_role_fedora4, fedora_version: '4.7.5' }
    - { role: uclalib_role_clamav }
    - { role: uclalib_role_pip }
    - { role: uclalib_role_imagemagick }
    - { role: uclalib_role_libreoffice, libreoffice_version: '6.0.6' }
    - { role: uclalib_role_ffmpeg, ffmpeg_version: '4.0.2' }
    - { role: uclalib_role_fits, fits_version: '1.3.0' }
    - { role: uclalib_role_ruby, ruby_version: '2.5.1' }
    - { role: uclalib_role_passenger, passenger_version: '5.3.3' }
    - { role: uclalib_role_nodejs, nodejs_version: '8' }
    - { role: uclalib_role_yarn }
    - { role: uclalib_role_redis }
