# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

current_dir = File.dirname(File.expand_path(__FILE__))
configs = YAML.load_file("#{current_dir}/vagrant-config.yaml")

# before we even start, let's check to see if the vagrant-sshfs plugin is installed
unless Vagrant.has_plugin?('vagrant-sshfs')
    raise 'required plugin vagrant-sshfs is not installed! \nRecommended action: \ninstall the plugin with the following command:\n\n  vagrant plugin install vagrant-sshfs\n\nGentle reminder: also be sure to install the SSHFS package on your host OS.'
end

Vagrant.configure("2") do |config|
  config.vm.box = configs['project_owner'] + "/" + configs['project_name']

  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 80, host: 3000
  config.vm.network "forwarded_port", guest: 8080, host: 8984
  config.vm.network "forwarded_port", guest: 8983, host: 8983

  config.vm.synced_folder configs['project_name'], "/home/vagrant/" + configs['project_name'], create: true, type: "sshfs", reverse: true
  config.vm.synced_folder '.', '/vagrant', disabled: true

  if File.exists?(File.expand_path("~/.gitconfig"))
    config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"
  end

  if File.exists?(File.expand_path("~/.gitignore"))
    config.vm.provision "file", source: "~/.gitignore", destination: ".gitignore"
  end

  # It shouldn't take this long
  config.vm.boot_timeout = 600

  config.ssh.forward_agent = true
  config.ssh.shell="bash"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.name = configs['project_name']
  end

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define configs['project_name']

  # if we're running with vagrant-notify, send a notification that we're done, in case we've wandered off
  # https://github.com/fgrehm/vagrant-notify
  # NOTE: Currently this plugin only works on Linux or OSX hosts
  if Vagrant.has_plugin?('vagrant-notify')
      config.vm.provision :shell, :inline => "notify-send --urgency=critical -t 20000 " + configs['project_name'] + " is up!", run: "always"
  end

  # Message to display to user after 'vagrant up' completes
  config.vm.post_up_message = "Setup of " + configs['project_name'] + " is now COMPLETE!\nYou can SSH into the new VM via 'vagrant ssh'\n\nNote: To push to GitHub or deploy to a remote server,\nyou must have ssh-agent installed on your host machine"
end

